# -*- mode: zsh; -*-
# compinit and completion styles

# Tool completions generated by chezmoi run-scripts and externals.
# Prepended so they win over any same-named system-supplied completion.
fpath=("${ZDOTDIR}/completions.d" $fpath)

# Tab completions from brew
if [[ $OSTYPE == "darwin"* ]]; then
  if type brew &>/dev/null; then
    fpath+="$(brew --prefix)/share/zsh/site-functions"
  fi
fi

autoload -Uz compinit && compinit
zstyle ':completion:*' menu select                                          # select completions with arrow keys
zstyle ':completion:*' group-name ''                                        # group results by category
zstyle ':completion:::::' completer _expand _complete _ignored              # enable approximate matches for completion
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*:*:*:*:descriptions' format '%F{green}-- %d --%f'
autoload -U +X bashcompinit && bashcompinit
